site_name: Llama ITX
site_description: Project Documentation for Llama ITX
repo_url: https://github.com/t3hbeowulf/itxllama
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - FAQs: faq.md
  #- Building: building.md
  - User's Guide: user-guide.md
  #- License: 'https://github.com/t3hbeowulf/itxllama/blob/main/LICENSE'

theme: 
  name: mkdocs
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  user_color_mode_toggle: true
  color_mode: auto

# plugins:
#   - literate-nav:
#       nav_file: README.md
#       implicit_index: true

markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  # - pymdownx.highlight:
  #     use_pygments: false
  # - pymdownx.snippets
  # - pymdownx.superfences
  # - callouts
  # - mdx_gh_links:
  #     user: mkdocs
  #     repo: mkdocs
  # - mkdocs-click